//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_サーバーソフトウェアバージョンREL
    {
        public int JOB_サーバーソフトウェアバージョンID { get; set; }
        public Nullable<int> JOBID { get; set; }
        public Nullable<int> サーバーソフトウェアバージョンID { get; set; }
        public System.DateTime 登録日時 { get; set; }
        public string 登録者 { get; set; }
    
        public virtual JOBMST JOBMST { get; set; }
        public virtual サーバー_ソフトウェアバージョンREL サーバー_ソフトウェアバージョンREL { get; set; }
    }
}
