//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class サーバー_ソフトウェアバージョンREL
    {
        public サーバー_ソフトウェアバージョンREL()
        {
            this.JOB_サーバーソフトウェアバージョンREL = new HashSet<JOB_サーバーソフトウェアバージョンREL>();
        }
    
        public int サーバーソフトウェアバージョンID { get; set; }
        public int サーバーID { get; set; }
        public int ソフトウェアバージョンID { get; set; }
        public System.DateTime 登録日時 { get; set; }
        public string 登録者 { get; set; }
    
        public virtual ICollection<JOB_サーバーソフトウェアバージョンREL> JOB_サーバーソフトウェアバージョンREL { get; set; }
        public virtual サーバーMST サーバーMST { get; set; }
        public virtual ソフトウェアバージョンMST ソフトウェアバージョンMST { get; set; }
    }
}
