//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ソフトウェアMST
    {
        public ソフトウェアMST()
        {
            this.ソフトウェアバージョンMST = new HashSet<ソフトウェアバージョンMST>();
        }
    
        public int ソフトウェアID { get; set; }
        public string ソフトウェア名 { get; set; }
        public System.DateTime 登録日時 { get; set; }
        public string 登録者 { get; set; }
    
        public virtual ICollection<ソフトウェアバージョンMST> ソフトウェアバージョンMST { get; set; }
    }
}
